### ISSUE TITLE
cast typedefed value to uint failed

### ISSUE THREAD

**Issue by morya** [spf13/cast#203]
```go
package main

import (
	"fmt"

	"github.com/spf13/cast"
)

type Degree int

const (
	V1 Degree = 1 + iota
	V2
)

func main() {
	var c = cast.ToUint(V2)
	fmt.Println(c)
}
```

the output value turn out to be `0`

**Comment by rust17** [comment]
I have read the source code and the README, and I believe that this cast.ToUint() doesn't support user-defined types.

**Comment by morya** [comment]
thx, no `user-defined` support, my bad
