### ISSUE TITLE
cast.ToBool return wrong value for int

### ISSUE THREAD

**Issue by yibaoren** [spf13/cast#98]
![image](https://user-images.githubusercontent.com/25901324/83851018-4e360800-a744-11ea-8aa5-5a1c536aeb3b.png)

ToBoolE function can not recognize int64 nor int32, which result in  false return
I hope it will be fixed soon.

**Comment by sgsullivan** [comment]
I believe I also ran into this issue, for example:

```golang
package main

import (
        "fmt"
        "github.com/spf13/cast"
)

func main() {
        fmt.Printf("its %t\n", cast.ToBool(float64(1)))
}
```

prints `its false`. I've worked around it by casting to an int before bool.
